trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm install
    displayName: "npm install"

  - task: Bash@3
    inputs:
      targetType: "inline"
      script: |
        tokenJson=$(cat << EOS
        {
          "access_token": "ya29.a0Adw1xeW67nCJdysnFJdTjVWayoYQtOQe8FIeWadg-7mtYCqqg96y1MJHLg5RKurxhlsWYWfKjZC4pYNEJMhXxd2XMjIjgovUX4vHRFvFYUlppFCinFKBQBWOJy4mMu7P6hA4mXOCmK5MWPQECBpUrJh-vXzd5KkZRdw",
          "refresh_token": "1//0e24LN9CebKUfCgYIARAAGA4SNwF-L9IrsfwR8CPDf-CiQ23hbOzPPmd7W3SILksWgTEMQrfsUOKIeah0lQMaiX2k-DjyoKYm0-M"
        }
        EOS
        )
        echo "$tokenJson" > token.json
      workingDirectory: "$(System.DefaultWorkingDirectory)"

  - task: Bash@3
    inputs:
      targetType: "inline"
      script: |
        credential=$(cat << EOS
        {
          "installed": {
            "client_id": "250679229437-pj5uie7mo2vb9d3pvhilsa03d63oprad.apps.googleusercontent.com",
            "project_id": "quickstart-1550231045469",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_secret": "$(client_secret)",
            "redirect_uris": ["urn:ietf:wg:oauth:2.0:oob", "http://localhost"]
          }
        }
        EOS
        )
        echo "$credential" > oauthCredential.json
      workingDirectory: "$(System.DefaultWorkingDirectory)"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      ArtifactName: "drop"
      publishLocation: "Container"
